# -*- coding: utf-8 -*-
# Developed by Bizople Solutions Pvt. Ltd.
# See LICENSE file for full copyright and licensing details
{
    'name': 'Theme Snazzy',
    'category': 'Theme/eCommerce',
    'version': '18.0.0.12',
    'author': 'Bizople Solutions Pvt. Ltd.',
    'website': 'https://www.bizople.com',
    'summary': 'Theme Snazzy is featured with eCommerce functionalities and is fully responsive for all devices that can be used for Electronics, Furniture, Cosmetics, and related industries.',    
    'description': """Theme Snazzy is featured with eCommerce functionalities and is fully responsive for all devices that can be used for Electronics, Furniture, Cosmetics, and related industries.""",
    'depends': [
        'snazzy_theme_common',
    ],
    'data': [
            'views/assets.xml',
            'views/ecommerce_templates.xml',
            'views/shop_page_template.xml',
            'views/product_customize_template.xml',
            'views/product_page_template.xml',
            'views/product_banner_options.xml',
            'views/res_config.xml',
            'views/brand_view.xml',
            'views/coming_soon_template.xml',
            'views/404_template.xml',
            'views/thankyou_template.xml',
            'views/help_center_template.xml',
            'views/product_quick_view_template.xml',
            'views/pwa_shortcuts.xml',
            'views/dynamicslider.xml',
            'views/product_tab_view.xml',
            'views/product_service_view.xml',
            'views/product_pricelist_view.xml',
            
            'views/theme_snazzy_search.xml',
            'views/product_template_attribute_value_view.xml',
            'views/product_page_variant_img_template.xml',
            'views/product_compare_inherited.xml',
            'views/image_hotspot_options.xml',
            'views/snippet_options.xml',
            'views/shop_cart_sidebar.xml',
            'views/portal_template.xml',
            'views/sale_portal_templates_inherit.xml',
            'views/store_location.xml',
            'views/shop_outlets_template.xml',
            'views/checkout_pages_inherit.xml',
            'views/wishlist_page_inherited.xml',
            'views/saleorder_field_add.xml',
            'views/login_template_inherited.xml',
            'views/dynamic_config_template.xml',
            'views/configurator/product_configurator_template.xml',
            'views/configurator/category_configurator_template.xml',
            'views/configurator/brand_configurator_template.xml',
            'views/configurator/blog_configurator_template.xml',
            'views/menus.xml',
            
            # Inherited
            'views/inherited/blog_page_inherit.xml',
            'views/inherited/contact_us_template.xml',
            
            'views/homepages/typographys.xml',
            'views/homepages/offer_page.xml',

            # Headers
            'views/headers/header_common_template.xml',
            'views/headers/header_template1.xml',
            'views/headers/header_template2.xml',
            'views/headers/header_template3.xml',
            'views/headers/header_template4.xml',
            'views/headers/header_template5.xml',
            'views/headers/header_template6.xml',
            
            # Footers
            'views/footers/footer_template1.xml',
            'views/footers/footer_template2.xml',
            'views/footers/footer_template3.xml',
            'views/footers/footer_template4.xml',
            'views/footers/footer_template5.xml',
            'views/footers/footer_template6.xml',
            'views/footers/footer_template7.xml',
            'views/footers/footer_template8.xml',
            'views/footers/footer_template9.xml',

            # snippets
            'views/snippets/s_theme_snazzy_page_one.xml',
            'views/snippets/s_theme_snazzy_page_two.xml',
            'views/snippets/s_theme_snazzy_page_three.xml',
            'views/snippets/s_theme_snazzy_page_four.xml',
            'views/snippets/s_theme_snazzy_page_five.xml',
            'views/snippets/s_theme_snazzy_page_six.xml',
            'views/snippets/s_theme_snazzy_page_seven.xml',

            'views/snippets/s_biz_theme_snazzy_homepage_one_banner.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_banner_one.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_two_block_three_img.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_countdown_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_limited_edition_one.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_limited_edition_two.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_two_block_img.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_game_controller.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_new_arrivals_text_style.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_product_add_to_cart.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_hotspot_image.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_testimonial.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_news_letter.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_one_order_features.xml',
            
            'views/snippets/s_biz_theme_snazzy_electronic_homepage_two_banner.xml',
            'views/snippets/s_biz_theme_snazzy_electronics_homepage.xml',
            'views/snippets/s_biz_theme_snazzy_electronic_homepage_two_countdown_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_electronic_homepage_two_limited_edition_two.xml',
            'views/snippets/s_biz_theme_snazzy_electronic_homepage_two_news_letter.xml',
            'views/snippets/s_biz_theme_snazzy_electronic_homepage_two_testimonial.xml',

            'views/snippets/s_biz_theme_snazzy_two_banner_one.xml',
            'views/snippets/s_biz_theme_snazzy_two_banner_two.xml',
            'views/snippets/s_biz_theme_snazzy_two_better_quality.xml',
            'views/snippets/s_biz_theme_snazzy_two_hot_this_week.xml',
            'views/snippets/s_biz_theme_snazzy_two_our_story.xml',
            'views/snippets/s_biz_theme_snazzy_two_super_quality_shoes.xml',
            'views/snippets/s_biz_theme_snazzy_two_best_feature_in_shoes.xml',
            'views/snippets/s_biz_theme_snazzy_two_hostport_image.xml',
            'views/snippets/s_biz_theme_snazzy_two_special_offer.xml',
            'views/snippets/s_biz_theme_snazzy_two_order_features.xml',
            'views/snippets/s_biz_theme_snazzy_two_gallery.xml',
            'views/snippets/s_biz_theme_snazzy_two_hover_img_effect.xml',

            'views/snippets/s_biz_theme_snazzy_three_banner.xml',
            'views/snippets/s_biz_theme_snazzy_three_discover_our_collection.xml',
            'views/snippets/s_biz_theme_snazzy_three_new_collection.xml',
            'views/snippets/s_biz_theme_snazzy_three_wooden_bed.xml',
            'views/snippets/s_biz_theme_snazzy_three_hostport_image.xml',
            'views/snippets/s_biz_theme_snazzy_three_reviews_carousel.xml',
            'views/snippets/s_biz_theme_snazzy_three_get_inspired.xml',

            'views/snippets/s_biz_theme_snazzy_four_banner.xml',
            'views/snippets/s_biz_theme_snazzy_four_popular_categories.xml',
            'views/snippets/s_biz_theme_snazzy_four_countdown_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_four_order_features.xml',
            'views/snippets/s_biz_theme_snazzy_four_unique_needs_two_block.xml',
            'views/snippets/s_biz_theme_snazzy_four_about_video.xml',
            'views/snippets/s_biz_theme_snazzy_four_new_arrivals_text_style.xml',
            'views/snippets/s_biz_theme_snazzy_four_testimonial.xml',

            'views/snippets/s_biz_theme_snazzy_homepage_five_banner_two.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_five_six_block_img.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_five_every_cloud_intarsia_knit_jumper.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_five_two_block_img.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_five_two_block_section_one.xml',
            'views/snippets/s_biz_theme_snazzy_homepage_five_testimonial.xml',

            'views/snippets/s_biz_theme_snazzy_grocery_banner.xml',
            'views/snippets/s_biz_theme_snazzy_grocery_bg_img_shop_now.xml',
            'views/snippets/s_biz_theme_snazzy_grocery_three_block_shop_now.xml',
            'views/snippets/s_biz_theme_snazzy_grocery_organic_product.xml',
            'views/snippets/s_biz_theme_snazzy_grocery_two_block_shop_now.xml',
            'views/snippets/s_biz_theme_snazzy_grocery_high_quality_organic_product.xml',
            'views/snippets/s_biz_theme_snazzy_grocery_organic_vegitabels.xml',

            # snippets
            'views/snippets/s_biz_theme_snazzy_images_wall.xml',

            'views/snippets/s_configurator_snippet_style1.xml',
            'views/snippets/s_configurator_snippet_style2.xml',
            'views/snippets/s_configurator_snippet_style3.xml',
            'views/snippets/s_configurator_snippet_style4.xml',
            'views/snippets/s_configurator_snippet_style5.xml',
            'views/snippets/s_configurator_snippet_style6.xml',
            'views/snippets/s_configurator_snippet_style7.xml',
            'views/snippets/s_configurator_snippet_style8.xml',
            'views/snippets/s_configurator_snippet_style9.xml',
            'views/snippets/s_configurator_snippet_style10.xml',
            'views/snippets/snazzy_newsletter_subscribe_popup.xml',
            'views/snippets/snazzy_offer_popup.xml',
            'views/snazzy_new_page_templates.xml',
            
            'views/theme_snazzy_inherited.xml',
    ],
    'demo': [
        'data/menu_data.xml',
    ],
    'assets': {
        'web._assets_primary_variables':[
            ('prepend','/theme_snazzy/static/src/scss/color_variables.scss'),
            "/theme_snazzy/static/src/scss/theme_variable.scss",
            "/theme_snazzy/static/src/scss/font_icon_mixin.scss",
        ],
        'web.assets_frontend': [
            "/theme_snazzy/static/src/css/owl.carousel.css",

            # Icons Fonts
            "/theme_snazzy/static/lib/RemixIcon/remixicon.css",

            # Headers 
            '/theme_snazzy/static/src/scss/headers/megamenu.scss',
            '/theme_snazzy/static/src/scss/headers/header_common.scss',
            '/theme_snazzy/static/src/scss/headers/header1.scss',
            '/theme_snazzy/static/src/scss/headers/header2.scss',
            '/theme_snazzy/static/src/scss/headers/header3.scss',
            '/theme_snazzy/static/src/scss/headers/header4.scss',
            '/theme_snazzy/static/src/scss/headers/header5.scss',
            '/theme_snazzy/static/src/scss/headers/header6.scss',
            '/theme_snazzy/static/src/scss/headers/sidebar.scss',
            '/theme_snazzy/static/src/scss/headers/mobile_bottom_bar.scss',
            
            # Footers
            '/theme_snazzy/static/src/scss/footers/footer1.scss',
            '/theme_snazzy/static/src/scss/footers/footer2.scss',
            '/theme_snazzy/static/src/scss/footers/footer_common.scss',
            
            # Homepages
            "/theme_snazzy/static/src/scss/homepages/electronic_homepage.scss",
            "/theme_snazzy/static/src/scss/homepages/furniture_homepage.scss",
            "/theme_snazzy/static/src/scss/homepages/shoes_homepage.scss",
            "/theme_snazzy/static/src/scss/homepages/cosmetic_homepage.scss",
            "/theme_snazzy/static/src/scss/homepages/fashion_homepage.scss",
            "/theme_snazzy/static/src/scss/homepages/grocery_homepage.scss",
            "/theme_snazzy/static/src/scss/homepages/offer_page.scss",

            # snippets
            "/theme_snazzy/static/src/scss/snippets/s_biz_theme_snazzy_images_wall.scss",

            # Other Pages
            '/theme_snazzy/static/src/scss/configurator/biz_mixins.scss',
            "/theme_snazzy/static/src/scss/common.scss",
            "/theme_snazzy/static/src/scss/shop_page.scss",
            "/theme_snazzy/static/src/scss/product_page.scss",
            '/theme_snazzy/static/src/scss/compare_products.scss',
            '/theme_snazzy/static/src/scss/blog_page.scss',
            '/theme_snazzy/static/src/scss/quick_view.scss',
            '/theme_snazzy/static/src/scss/wishlist_page.scss',
            '/theme_snazzy/static/src/scss/login_page.scss',
            '/theme_snazzy/static/src/scss/configurator/product_styles.scss',
            '/theme_snazzy/static/src/scss/configurator/categ_styles.scss',
            '/theme_snazzy/static/src/scss/configurator/brand_styles.scss',
            '/theme_snazzy/static/src/scss/configurator/blog_styles.scss',
            '/theme_snazzy/static/src/scss/shop_cart_sidebar.scss',
            '/theme_snazzy/static/src/scss/optional_product_popup.scss',
            '/theme_snazzy/static/src/scss/image_hotspot.scss',
            '/theme_snazzy/static/src/scss/product_banner.scss',
            '/theme_snazzy/static/src/scss/portal.scss',
            '/theme_snazzy/static/src/scss/shopby.scss',
            '/theme_snazzy/static/src/scss/checkout_pages.scss',
            '/theme_snazzy/static/src/scss/help_center.scss',
            '/theme_snazzy/static/src/scss/coming-soon.scss',
            '/theme_snazzy/static/src/scss/contactus.scss',
            'theme_snazzy/static/src/scss/shop_outlets_template.scss',
            'theme_snazzy/static/src/scss/dynamic_configurator_snippets.scss',
            
            # Js
            "/theme_snazzy/static/src/js/product_banner.js",
            "/theme_snazzy/static/src/js/product_image_hotspot.js",
            "/theme_snazzy/static/src/js/common.js",
            '/theme_snazzy/static/src/js/counter_time.js',
            '/theme_snazzy/static/src/js/variant_mixin.js',
            "/theme_snazzy/static/src/js/snazzy_sale.js",
            "/theme_snazzy/static/src/js/navbar.js",
            "/theme_snazzy/static/src/js/product_brand.js",
            "/theme_snazzy/static/src/js/infinite_product_load.js",
            "/theme_snazzy/static/src/js/modal_popup.js",
            "/theme_snazzy/static/src/js/wishlist_page.js",
            "/theme_snazzy/static/src/js/product_variant.js",
            "/theme_snazzy/static/src/js/portal.js",
            "/theme_snazzy/static/src/js/pwaapp.js",
            "/theme_snazzy/static/src/js/product_search.js",
            "/theme_snazzy/static/src/js/store_location_data.js",
            "/theme_snazzy/static/src/js/dynamic_config_frontend.js",
            "/theme_snazzy/static/src/js/product_color_change.js",
            "/theme_snazzy/static/src/js/mobile.js",
            
            #xml
            # Common
            "/theme_snazzy/static/src/js/fonts.js",
            "/theme_snazzy/static/src/css/owl.carousel.css",
            "/theme_snazzy/static/lib/RemixIcon/remixicon.css",
            "/theme_snazzy/static/src/scss/dynamic_configurator.scss",
            "/theme_snazzy/static/src/scss/configurator/biz_mixins.scss",
            "/theme_snazzy/static/src/scss/configurator/product_styles.scss",
            '/theme_snazzy/static/src/scss/configurator/categ_styles.scss',
            '/theme_snazzy/static/src/scss/configurator/brand_styles.scss',
            "/theme_snazzy/static/src/scss/common.scss",
            '/theme_snazzy/static/src/scss/configurator/blog_styles.scss',
            '/theme_snazzy/static/src/xml/website_sale_rendermodal.xml',
             ('include', 'theme_snazzy.webclientmulti'),
        ],
        # 'web.assets_backend': [
        'website.assets_wysiwyg':[
            # Common
            "website_sale/static/src/scss/product_configurator.scss",
            "/theme_snazzy/static/src/js/fonts.js",
            "/theme_snazzy/static/src/css/owl.carousel.css",
            "/theme_snazzy/static/lib/RemixIcon/remixicon.css",
            "/theme_snazzy/static/src/scss/dynamic_configurator.scss",
            "/theme_snazzy/static/src/scss/configurator/biz_mixins.scss",
            "/theme_snazzy/static/src/scss/configurator/product_styles.scss",
            '/theme_snazzy/static/src/scss/configurator/categ_styles.scss',
            '/theme_snazzy/static/src/scss/configurator/brand_styles.scss',
            "/theme_snazzy/static/src/scss/common.scss",
            '/theme_snazzy/static/src/scss/configurator/blog_styles.scss',

            '/theme_snazzy/static/src/js/snippetoptions/image_hotspot_options.js',
            '/theme_snazzy/static/src/js/snippetoptions/product_banner_option.js',
            '/theme_snazzy/static/src/js/snippetoptions/dynamic_config_tool.js',
            '/theme_snazzy/static/src/js/megamenu.js',
             ('include', 'theme_snazzy.webclientmulti'),
        ],
        'theme_snazzy.webclientmulti': [
            # '/web/static/lib/jquery/jquery.js',
            '/theme_snazzy/static/lib/owlcarousel/owl.carousel.min.js',
            "/theme_snazzy/static/lib/lazyload/lazyload.js",
            #  ('include', 'web_editor.wysiwyg_iframe_editor_assets'),
        ],
        'web_editor.assets_wysiwyg': [
            '/theme_snazzy/static/src/xml/dynamic_config_tool.xml',
            '/theme_snazzy/static/src/xml/product_banner.xml',
            '/theme_snazzy/static/src/xml/image_hotspot_info.xml',
            '/theme_snazzy/static/src/js/snippetoptions/icon_pack.js',
        ],
       
        'web_editor.assets_snippets_menu': [
            '/theme_snazzy/static/src/js/snippetoptions/bizcommon_editor.js', 
        ],
        'web_editor.assets_media_dialog': [
            '/theme_snazzy/static/src/js/snippetoptions/icon_selector.js',
        ],
        # 'website.assets_wysiwyg':[
        #     '/theme_snazzy/static/src/js/snippetoptions/image_hotspot_options.js',
        #     '/theme_snazzy/static/src/js/snippetoptions/product_banner_option.js',
        #     '/theme_snazzy/static/src/js/snippetoptions/dynamic_config_tool.js',
        # ],
       
    },
    'live_test_url': 'https://www.bizople.com/r/snazzy18',
    'images': [
        'static/description/snazzy_cover.jpg',
        'static/description/snazzy_screenshot.gif',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'OPL-1',
    'price': 145,
    'currency': 'EUR',
}